# Generated by Django 2.0.1 on 2018-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_icon_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('summoner_level', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('summoner_id', models.IntegerField()),
                ('revision_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('summoner_id', 'account_id', 'name')},
        ),
    ]
