# Generated by Django 2.0.1 on 2018-05-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180501_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChampionStats',
        ),
    ]
