# Generated by Django 2.0.1 on 2018-05-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_championstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.BigIntegerField(unique=True)),
                ('version', models.CharField(max_length=30)),
                ('armorperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hpperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attackdamage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mpperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attackspeedoffset', models.DecimalField(decimal_places=3, max_digits=10)),
                ('armor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hp', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hpregenperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('spellblock', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attackrange', models.DecimalField(decimal_places=3, max_digits=10)),
                ('movespeed', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attackdamageperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mpregenperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mp', models.DecimalField(decimal_places=3, max_digits=10)),
                ('spellblockperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('crit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mpregen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('attackspeedperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hpregen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('critperlevel', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
